### PR TITLE
🚛 Introduce `src`-Layout / Restructure Template Repo

### PR DESCRIPTION
**Pull request by hf-kklein**
This PR is to address our latest findings on "the best python setup" possible ;)

### CODE REVIEW

**Comment by hf-kklein** [comment]
@hf-krechan did you try with "extraPath"? https://stackoverflow.com/questions/60857618/adding-source-root-to-python-project-structure-vs-code or [`PYTHONPATH` in `.env`](https://stackoverflow.com/a/50107230/10009545)

**Comment by hf-krechan** [comment]
mmh okay, it works if you create a `.env` file in the root directory of the repository and add the following
```
PYTHONPATH=src
```

but I feel not so happy about this solution.
This SO entry tells us also what PyCharme is doing if you tick the checkbox `"Add Content Roots to PYTHONPATH"`
And it tells us why it is good and bad at the same time ^^

**Comment by hf-kklein** [comment]
In Pycharm we "solve" this issue by declaring the directory as src-root, just what it is:
https://github.com/Hochfrequenz/python_template_repository/commit/8c85f7ac60cc32fc6e5e8736ee528e5cfe73d5a5

**Review by hf-krechan — APPROVED** [review]
I approve this PR now.
At the end I am not happy with this "solution". But it's getting the job done.
For the VS Code users I added a step to create a `.env` file.

**Pull request merged**
